### ISSUE TITLE
Selecting walls & curved walls sometimes causes an exception.

### ISSUE THREAD

**Issue by dimension-breaker** [AyazLab/MazeMaker#4]
MazeMaker: [Bug] Selecting walls & curved walls sometimes causes an exception.

**Comment by AdrianCurtin** [comment]
https://github.com/AyazLab/MazeMaker/blob/4c3963bc0478308e3471965c40dbd76f54409e1b/MazeMaker/Main.cs#L3641

**Comment by dimension-breaker** [comment]
https://github.com/AyazLab/MazeMaker/blob/349a30817ace1b180946ac8064ce394f784ca386/MazeMaker/Main.cs#L3461


null reference error
