### ISSUE TITLE
Importing files and Saving mazes use the same "last path"

### ISSUE THREAD

**Issue by AdrianCurtin** [AyazLab/MazeMaker#6]
When adding an image/model resource, the previous directory used is retained. This should be stored seaparately for the maze file itself (ie: clicking saveas should open in the same directory as the main file)

**Comment by lm3267** [comment]
separate vars for mazes and assets

**Comment by lm3267** [comment]
package, import as MazX package, open should use the last directory used for maze as well

**Comment by lm3267** [comment]
when use open, assets folder shouldnt reset, but maze should reset
